# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  ## lily58 left firmware (nice!view)
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view

  ## lily58 right firmware (nive!view)
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view

  ## lily58 left firmware (generic oled)
  - board: nice_nano_v2
    shield: lily58_left

  ## lily58 right firmware (generic oled)
  - board: nice_nano_v2
    shield: lily58_right

  ## Corne Left (generic oled)
  - board: nice_nano_v2
    shield: corne_left 

  ## Corne Right (generic oled)  
  - board: nice_nano_v2
    shield: corne_right 

  ## reset firmware
  - board: nice_nano_v2
    shield: settings_reset
